spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/books"
    username: "postgres"
    password: "xxxxxxxx"
  jpa:
    hibernate:
      ddl-auto: create

